version: '3'

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    restart: always
    container_name: tickets_db
    network_mode: bridge
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aviatickets
